# version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

handlers:

- url: /static
  static_dir: static
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  
- url: /favicon.png
  static_files: static/favicon.png
  upload: static/favicon.png
  mime_type: image/png
  
# http://mathiasbynens.be/notes/touch-icons
- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed.png
  mime_type: image/png
  
- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed.png
  mime_type: image/png

- url: /apple-touch-icon-72x72-precomposed\.png
  static_files: static/apple-touch-icon-72x72-precomposed.png
  upload: static/apple-touch-icon-72x72-precomposed.png
  mime_type: image/png

- url: /apple-touch-icon-114x114-precomposed\.png
  static_files: static/apple-touch-icon-114x114-precomposed.png
  upload: static/apple-touch-icon-114x114-precomposed.png
  mime_type: image/png

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /sitemap\.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
 
- url: .*
  script: main.app
