#!/usr/bin/env python
import cantinotti_jase_2014
import bhatla_circimaging_2012
import gentles_jacc_2012
import dallaire_jase_2011
import foster_circ_2008
import lytrivi_jase_2011
import neilan_eje_2009
import olivieri_jase_2009
import pettersen_jase_2008
import mccrindle_circ_2007
import colan_jacc_2006
import warren_heart_2006
import zilberman_pedcard_2005
import kampmann_heart_2000
import daubeney_cardyoung_1999
import overbeek_eje_2006
import pfaffenberger_circimaging_2013
import koestenberger_ajc_2012
import eidem_jase_2004
import campens_ajc_2014
import gautier_ajc_2010
import jain_jase_2014
import cantinotti_jase_2014_dec
import dallaire_circimaging_2015
import dallaire_pedcard_2015
import koestenberger_ajc_2014
import quezada_ajmg_2015
import dallaire_jase_2016
import kobayashi_jase_2016
import koestenberger_circimaging_2017
import dijkema_jase_2017
import choudhry_jase_2017
import lopez_circimaging_2017
import cantinotti_jcard_2017
import rajagopal_pedcard_2018
import yao_jase_2019



import logging

zLimit = 1.96

REFS = {
    'cantinotti-jase-2014': cantinotti_jase_2014,
    'cantinotti-jase-2014-december': cantinotti_jase_2014_dec,
    'bhatla-circimaging-2012': bhatla_circimaging_2012,
    'colan-jacc-2006': colan_jacc_2006,
    'dallaire-jase-2011': dallaire_jase_2011,
    'daubeney-cardyoung-1999': daubeney_cardyoung_1999,
    'foster-circ-2008': foster_circ_2008,
    'gentles-jacc-2012': gentles_jacc_2012,
    'kampmann-heart-2000': kampmann_heart_2000,
    'lytrivi-jase-2011': lytrivi_jase_2011,
    'mccrindle-circ-2007': mccrindle_circ_2007,
    'neilan-eje-2009': neilan_eje_2009,
    'olivieri-jase-2009': olivieri_jase_2009,
    'pettersen-jase-2008': pettersen_jase_2008,
    'warren-heart-2006' : warren_heart_2006,
    'zilberman-pedcard-2005': zilberman_pedcard_2005,
    'overbeek-eje-2006': overbeek_eje_2006,
    'pfaffenberger-circimaging-2013': pfaffenberger_circimaging_2013,
    'koestenberger-ajc-2012': koestenberger_ajc_2012,
    'eidem-jase-2004': eidem_jase_2004,
    'campens-ajc-2014': campens_ajc_2014,
    'gautier-ajc-2010': gautier_ajc_2010,
    'jain-jase-2014': jain_jase_2014,
    'dallaire-circimaging-2015': dallaire_circimaging_2015,
    'dallaire-pedcard-2015': dallaire_pedcard_2015,
    'koestenberger-ajc-2014': koestenberger_ajc_2014,
    'quezada-ajmg-2015': quezada_ajmg_2015,
    'dallaire-jase-2016': dallaire_jase_2016,
    'kobayashi-jase-2016': kobayashi_jase_2016,
    'koestenberger-circimaging-2017': koestenberger_circimaging_2017,
    'dijkema-jase-2017': dijkema_jase_2017,
    'choudhry-jase-2017': choudhry_jase_2017,
    'lopez-circimaging-2017': lopez_circimaging_2017,
    'cantinotti-jcard-2017': cantinotti_jcard_2017,
    'rajagopal-pedcard-2018': rajagopal_pedcard_2018,
    'yao-jase-2019': yao_jase_2019

}

def AvilableSites():
    temp = []
    for ref in REFS.values():
        for site in ref.sites:
            temp.append(site)
    #make this a unique list
    temp = list(set(temp))
    return [getattr(sites, site) for site in temp]


'''The canonical listing of all the available echo measurements

each site is a dict with the following pattern:

site = {'id': '', #for generating html inputs (name/id)
        'short_name': '', #for input labels
        'long_name': '', #for report/page titles
        'timing': '', #systole or diastole
        'units': '', #mm, ml, cm/sec, etc.
        'landmark': '', #'leaflet hinge points', 'anterior to RPA', etc
        'category': '', #one of [Atria, Aorta, AV Valves, etc]
        'modality': '', #one of [M-Mode, 2D, Doppler, etc]
        }

'''
MEASUREMENTS = [
    # M-modes
    {'id': 'rvawd_mm',
     'short_name': 'RVAW D',
     'long_name': 'RV Anterior Wall Diastolic Dimension',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'parasternal',
     'landmark': 'RV free wall',
     'category': 'Right Ventricle',
     'modality': 'M-Mode',
     },
    {'id': 'rvd_mm',
      'short_name': 'RV D',
      'long_name': 'RV End Diastolic Dimension',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'parasternal',
      'landmark': 'RV free wall to RV septal surface',
      'category': 'Right Ventricle',
      'modality': 'M-Mode',
      },
  {'id': 'la_mm',
      'short_name': 'LA Diam.',
      'long_name': 'Left Atrial Diameter',
      'timing': 'systole',
      'units': 'mm',
      'view': 'parasternal',
      'landmark': 'AP diameter at level of aortic root',
      'category': 'Atria',
      'modality': 'M-Mode',
      },
  {'id': 'ivsd_mm',
      'short_name': 'IVSd',
      'long_name': 'Interventricular Septum, Diastole',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'parasternal',
      'landmark': 'RV endocardial surface to LV endocardial surface',
      'category': 'Left Ventricle',
      'modality': 'M-Mode',
      },
  {'id': 'lvedd_mm',
      'short_name': 'LVEDd',
      'long_name': 'LV End-Diastolic Diameter',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'parasternal',
      'landmark': 'posterior septal surface to anterior surface of posterior wall; excluding papillary muscles',
      'category': 'Left Ventricle',
      'modality': 'M-Mode',
      },
  {'id': 'lvpwd_mm',
      'short_name': 'LVPWd',
      'long_name': 'LV Posterior Wall, Diastole',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'parasternal',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': 'M-Mode',
      },
  {'id': 'ivss_mm',
      'short_name': 'IVSs',
      'long_name': 'Interventricular Septum, Systole',
      'timing': 'systole',
      'units': 'mm',
      'view': 'parasternal',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': 'M-Mode',
      },
  {'id': 'lvesd_mm',
      'short_name': 'LVESd',
      'long_name': 'LV End-Systolic Diameter',
      'timing': 'systole',
      'units': 'mm',
      'view': 'parasternal',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': 'M-Mode',
      },
  {'id': 'lvpws_mm',
      'short_name': 'LVPWs',
      'long_name': 'LV Posterior Wall, Systole',
      'timing': 'systole',
      'units': 'mm',
      'view': 'parasternal',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': 'M-Mode',
      },
  {'id': 'lvm_mm',
      'short_name': 'LV Mass',
      'long_name': 'LV Mass',
      'timing': 'diastole',
      'units': 'g',
      'view': 'parasternal',
      'landmark': 'see: IVSd, LVEDD, and LVPWd',
      'category': 'Left Ventricle',
      'modality': 'M-Mode',
      },
#2-D Linear Measurements
#Left heart
  {'id': 'la',
      'short_name': 'LA Diam.',
      'long_name': 'Left Atrial Diameter',
      'timing': 'systole',
      'units': 'mm',
      'view': 'parasternal',
      'landmark': 'largest A-P diameter',
      'category': 'Atria',
      'modality': '2D',
      },
  {'id': 'la_major_a4c',
      'short_name': 'LA Major Diameter',
      'long_name': 'LA Major Diameter',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'maximal distance from the center of the mitral annulus to the center of the superior LA wall, parallel to the interatrial septum',
      'category': 'Left Atrium',
      'modality': '2D'
    },
  {'id': 'la_minor_a4c',
      'short_name': 'LA Minor Diameter',
      'long_name': 'LA Minor Diameter',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'maximal distance from the atrial septum to the lateral atrial wall',
      'category': 'Left Atrium',
      'modality': '2D'
    },
  {'id': 'la_area_a4c',
      'short_name': 'LA Area',
      'long_name': 'LA Area',
      'timing': 'systole',
      'units': 'cm^2',
      'view': 'A4C',
      'landmark': 'endocardial surface, from the lateral aspect of the mitral annulus to the septal aspect, excluding the pulmonary veins and appendage',
      'category': 'Left Atrium',
      'modality': '2D'
  },
  {'id': 'mvd_l',
      'short_name': 'MV, Lateral',
      'long_name': 'Mitral Valve, Lateral',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'leaflet hingepoints',
      'category': 'AV Valves',
      'modality': '2D',
      },
  {'id': 'mvd_ap',
      'short_name': 'MV, AP',
      'long_name': 'Mitral Valve, Antero-Posterior',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'PLAX',
      'landmark': 'leaflet hingepoints',
      'category': 'AV Valves',
      'modality': '2D',
      },
  {'id': 'mv_area',
     'short_name': 'MV, Area',
     'long_name': 'Mitral Valve Area',
     'timing': 'diastole',
     'units': 'cm^2',
     'view': '(derived)',
     'landmark': 'n/a',
     'category': 'AV Valves',
     'modality': '2D',
     },
    {'id': 'ivsd_psax',
     'short_name': 'IVSd',
     'long_name': 'Interventricular Septum, Diastole',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PSAX',
     'landmark': 'RV endocardial surface to LV endocardial surface',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
    {'id': 'ivsd_plax',
     'short_name': 'IVSd',
     'long_name': 'Interventricular Septum, Diastole',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'RV endocardial surface to LV endocardial surface',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
    {'id': 'ivss_plax',
     'short_name': 'IVSs',
     'long_name': 'Interventricular Septum, Systole',
     'timing': 'systole',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'RV endocardial surface to LV endocardial surface',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
    {'id': 'lvedd_psax',
     'short_name': 'LVEDd',
     'long_name': 'LV End Diastolic Diameter',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PSAX',
     'landmark': 'septal endocardial surface to posterior wall endocardial surface; just below mitral annulus',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
    {'id': 'lvedd_plax',
     'short_name': 'LVEDd',
     'long_name': 'LV End Diastolic Diameter',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'septal endocardial surface to posterior wall endocardial surface; just below mitral annulus',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
    {'id': 'lvesd_psax',
     'short_name': 'LVESd',
     'long_name': 'LV End Systolic Diameter',
     'timing': 'systole',
     'units': 'mm',
     'view': 'PSAX',
     'landmark': 'septal endocardial surface to posterior wall endocardial surface; just below mitral annulus',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
    {'id': 'lvesd_plax',
     'short_name': 'LVESd',
     'long_name': 'LV End Systolic Diameter',
     'timing': 'systole',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'septal endocardial surface to posterior wall endocardial surface; just below mitral annulus',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
    {'id': 'lvpwd_psax',
     'short_name': 'LVPWd',
     'long_name': 'LV Posterior Wall, Diastole',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PSAX',
     'landmark': 'posterior wall endocardial surface to epicardial surface',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
    {'id': 'lvpwd_plax',
     'short_name': 'LVPWd',
     'long_name': 'LV Posterior Wall, Diastole',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'posterior wall endocardial surface to epicardial surface',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
    {'id': 'lvpws_plax',
     'short_name': 'LVPWs',
     'long_name': 'LV Posterior Wall, Systole',
     'timing': 'systole',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'posterior wall endocardial surface to epicardial surface',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
  {'id': 'lv_eda_psax',
     'short_name': 'LV Area, ED (SAX)',
     'long_name': 'LV Area, End-Diastole (SAX)',
     'timing': 'diastole',
     'units': 'cm^2',
     'view': 'PSAX',
     'landmark': 'LV short axis endocardial area',
     'category': 'Left Ventricle',
     'modality': '2D',
  },
  {'id': 'lv_eda_epi_psax',
     'short_name': 'LV Epicardial Area, ED (SAX)',
     'long_name': 'LV Epicardial Area, End-Diastole (SAX)',
     'timing': 'diastole',
     'units': 'cm^2',
     'view': 'PSAX',
     'landmark': 'LV short axis epicardial area',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
  {'id': 'lv_maj_ed_a4c',
      'short_name': 'LV Major, ED (A4C)',
      'long_name': 'LV Major, End-Diastole (A4C)',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'basal border (line connecting the MV annular hinge points) midpoint to the apical endocardium',
      'category': 'Left Ventricle',
      'modality': '2D'
  },
  {'id': 'lv_maj_epi_ed_a4c',
     'short_name': 'LV Major Epi, ED (A4C)',
     'long_name': 'LV Major, Epicardial, End-Diastole (A4C)',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'A4C',
     'landmark': 'basal border (line connecting the MV annular hinge points) midpoint to the apical epicardium',
     'category': 'Left Ventricle',
     'modality': '2D'
   },
  {'id': 'lv_eda_a4c',
      'short_name': 'LV Area, End-Diastole (A4C)',
      'long_name': 'LV Area, End-Diastole (A4C)',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'LV endocardial borders (excluding the papillary muscles)',
      'category': 'Left Ventricle',
      'modality': '2D'
  },
  {'id': 'lv_maj_es_a4c',
      'short_name': 'LV Major, End-Systole (A4C)',
      'long_name': 'LV Major Diameter, End-Systole (A4C)',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'basal border (line connecting the MV annular hinge points) midpoint to the apical endocardium',
      'category': 'Left Ventricle',
      'modality': '2D'
  },
  {'id': 'lv_esa_a4c',
      'short_name': 'LV Area, End-Systole (A4C)',
      'long_name': 'LV Area, End-Systole (A4C)',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'LV endocardial borders (excluding the papillary muscles)',
      'category': 'Left Ventricle',
      'modality': '2D'
  },
  {'id': 'lv_maj_ed_a2c',
      'short_name': 'LV Major, End-Diastole (A2C)',
      'long_name': 'LV Major Diameter, End-Diastole (A2C)',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'A2C',
      'landmark': 'basal border (line connecting the MV annular hinge points) midpoint to the apical endocardium',
      'category': 'Left Ventricle',
      'modality': '2D'
  },
  {'id': 'lv_eda_a2c',
      'short_name': 'LV Area, End-Diastole (A2C)',
      'long_name': 'LV Area, End-Diastole (A2C)',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'A2C',
      'landmark': 'LV endocardial borders (excluding the papillary muscles)',
      'category': 'Left Ventricle',
      'modality': '2D'
  },
  {'id': 'lv_maj_es_a2c',
      'short_name': 'LV Major, End-Systole (A2C)',
      'long_name': 'LV Major Diameter, End-Systole (A2C)',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A2C',
      'landmark': 'basal border (line connecting the MV annular hinge points) midpoint to the apical endocardium',
      'category': 'Left Ventricle',
      'modality': '2D'
  },
  {'id': 'lv_esa_a2c',
      'short_name': 'LV Area, End-Systole (A2C)',
      'long_name': 'LV Area, End-Systole (A2C)',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A2C',
      'landmark': 'LV endocardial borders (excluding the papillary muscles)',
      'category': 'Left Ventricle',
      'modality': '2D'
  },
#volumes
  {'id': 'lav',
      'short_name': 'LA Vol.',
      'long_name': 'LA Volume',
      'timing': 'systole',
      'units': 'ml',
      'view': 'A4C',
      'landmark': '',
      'category': 'Atria',
      'modality': '2D',
      },
  {'id': 'lvedv',
      'short_name': 'LVEDV',
      'long_name': 'LV End-Diastolic Volume',
      'timing': 'diastole',
      'units': 'ml',
      'view': 'apical, PSAX, or subcostal',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': '2D',
      },
  {'id': 'lvedv_epi',  # for Boston Childrens' bullet' mass
     'short_name': 'LVEDV EPI',
     'long_name': 'LV End-Diastolic Volume, Epicardium',
     'timing': 'diastole',
     'units': 'ml',
     'view': 'apical, PSAX, or subcostal',
     'landmark': '',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
  {'id': 'lvesv',
      'short_name': 'LVESV',
      'long_name': 'LV End-Systolic Volume',
      'timing': 'systole',
      'units': 'ml',
      'view': 'apical',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': '2D',
      },
    {'id': 'lvef',
     'short_name': 'LV EF',
     'long_name': 'LV Ejection Fraction',
     'timing': '',
     'units': '%',
     'view': '',
     'landmark': '',
     'category': 'Left Ventricle',
     'modality': '2D',
     },
#lvm
  {'id': 'lvm_2d',
      'short_name': 'LV Mass',
      'long_name': 'LV Mass',
      'timing': 'diastole',
      'units': 'g',
      'view': 'parasternal, apical',
      'landmark': 'see components: PSAX Epi area, PSAX endo area, LV Major',
      'category': 'Left Ventricle',
      'modality': '2D',
      },
# derived LV ratios
    {
        'id': 'lv_mass_vol_ratio',
        'short_name': 'LV Mass:Vol',
        'long_name': 'LV Mass to Volume Ratio',
        'timing': 'diastole',
        'units': '',
        'view': '',
        'landmark': 'LV Mass/EDV',
        'category': 'Left Ventricle',
        'modality': '2D'
    },
    {
        'id': 'lvpw_lvedd_ratio',
        'short_name': 'LVPWd:LVEDD',
        'long_name': 'LV Posterior Wall to EDD Ratio',
        'timing': 'diastole',
        'units': '',
        'view': '',
        'landmark': 'LVPWd/LVEDD',
        'category': 'Left Ventricle',
        'modality': '2D'
    },
    {'id': 'lv_sphere_idx',
      'short_name': 'LV Sphericity',
      'long_name': 'LV Sphericity Index',
      'timing': 'diastole',
      'units': '',
      'view': 'SAX, A4C',
      'landmark': 'LV Major/Minor',
      'category': 'Left Ventricle',
      'modality': '2D'
    },
    {'id': 'lvot_nos',
     'short_name': 'LVOT',
     'long_name': 'Left Ventricular Outflow Tract',
     'timing': 'landmarks not specified in reference',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'timing not specified in reference',
     'category': 'Outlets',
     'modality': '2D',
     },
  {'id': 'aov',
      'short_name': 'AOV',
      'long_name': 'Aortic Valve Annulus',
      'timing': 'systole',
      'units': 'mm',
      'view': 'PLAX',
      'landmark': 'leaflet hingepoints',
      'category': 'Outlets',
      'modality': '2D',
  },
  {'id': 'aov_d',
     'short_name': 'AOV (d)',
     'long_name': 'Aortic Valve Annulus (d)',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'leaflet hingepoints',
     'category': 'Outlets',
     'modality': '2D',
   },
  {'id': 'lmca',
      'short_name': 'LMCA',
      'long_name': 'Left Main Coronary Artery',
      'timing': 'maximum diameter',
      'units': 'mm',
      'view': 'PSAX',
      'landmark': '',
      'category': 'Coronary Arteries',
      'modality': '2D',
      },
  {'id': 'lad',
      'short_name': 'LAD',
      'long_name': 'Left Anterior Descending Coronary Artery',
      'timing': 'maximum diameter',
      'units': 'mm',
      'view': 'PSAX',
      'landmark': '',
      'category': 'Coronary Arteries',
      'modality': '2D',
      },
  {'id': 'circ',
      'short_name': 'Circ.',
      'long_name': 'Circumflex Coronary Artery',
      'timing': 'maximum diameter',
      'units': 'mm',
      'view': 'PSAX',
      'landmark': '',
      'category': 'Coronary Arteries',
      'modality': '2D',
      },
  {'id': 'prox_rca',
      'short_name': 'Prox. RCA',
      'long_name': 'Proximal Right Coronary Artery',
      'timing': 'maximum diameter',
      'units': 'mm',
      'view': 'PSAX',
      'landmark': '',
      'category': 'Coronary Arteries',
      'modality': '2D',
      },
  {'id': 'mid_rca',
      'short_name': 'Mid RCA',
      'long_name': 'Mid Right Coronary Artery',
      'timing': 'maximum diameter',
      'units': 'mm',
      'view': 'PSAX',
      'landmark': '',
      'category': 'Coronary Arteries',
      'modality': '2D',
      },
  {'id': 'dist_rca',
      'short_name': 'Dist. RCA',
      'long_name': 'Distal Right Coronary Artery',
      'timing': 'maximum diameter',
      'units': 'mm',
      'view': '',
      'landmark': '',
      'category': 'Coronary Arteries',
      'modality': '2D',
      },
  {'id': 'sov',
      'short_name': 'SOV',
      'long_name': 'Sinus of Valsalva',
      'timing': 'systole',
      'units': 'mm',
      'view': 'PLAX',
      'landmark': 'largest diameter of sinus',
      'category': 'Aorta',
      'modality': '2D',
      },
  {'id': 'sov_d',
      'short_name': 'SOV',
      'long_name': 'Sinus of Valsalva (d)',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'PLAX',
      'landmark': 'largest diameter of sinus',
      'category': 'Aorta',
      'modality': '2D',
      },
  {'id': 'stj',
      'short_name': 'S-T Jct',
      'long_name': 'Sino-Tubular Junction',
      'timing': 'systole',
      'units': 'mm',
      'view': 'PLAX',
      'landmark': 'where the aortic sinuses end and the aorta becomes a tubular structure.',
      'category': 'Aorta',
      'modality': '2D',
      },
  {'id': 'stj_d',
      'short_name': 'S-T Jct',
      'long_name': 'Sino-Tubular Junction (d)',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'PLAX',
      'landmark': 'where the aortic sinuses end and the aorta becomes a tubular structure.',
      'category': 'Aorta',
      'modality': '2D',
      },
  {'id': 'aao',
      'short_name': 'AAO',
      'long_name': 'Ascending Aorta',
      'timing': 'systole',
      'units': 'mm',
      'view': 'PLAX or high RSB',
      'landmark': 'at the level of the RPA',
      'category': 'Aorta',
      'modality': '2D',
      },
  {'id': 'aao_d',
      'short_name': 'AAO',
      'long_name': 'Ascending Aorta (d)',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'PLAX or high RSB',
      'landmark': 'at the level of the RPA',
      'category': 'Aorta',
      'modality': '2D',
      },
    {'id': 'arch_nos',
     'short_name': 'Arch',
     'long_name': 'Aortic Arch',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'SSN',
     'landmark': 'landmarks not specified in reference',
     'category': 'Aorta',
     'modality': '2D',
     },
  {'id': 'prox_arch',
      'short_name': 'Prox. Trans. Arch',
      'long_name': 'Proximal Transverse Arch',
      'timing': 'systole',
      'units': 'mm',
      'view': 'SSN',
      'landmark': 'between 1st BCA and LCCA',
      'category': 'Aorta',
      'modality': '2D',
      },
  # {'id': 'mid_arch',
  #     'short_name': 'Mid Trans. Arch',
  #     'long_name': 'Mid Transverse Arch',
  #     'timing': 'systole',
  #     'units': 'mm',
  #     'view': 'SSN',
  #     'landmark': 'between LCCA and LSA',
  #     'category': 'Aorta',
  #     'modality': '2D',
  #     },
  {'id': 'dist_arch',
      'short_name': 'Dist. Trans. Arch',
      'long_name': 'Distal Transverse Arch',
      'timing': 'systole',
      'units': 'mm',
      'view': 'SSN',
      'landmark': 'between LCCA and LSA',
      'category': 'Aorta',
      'modality': '2D',
      },
  {'id': 'isthmus',
      'short_name': 'Isthmus',
      'long_name': 'Aortic Isthmus',
      'timing': 'systole',
      'units': 'mm',
      'view': 'SSN',
      'landmark': 'narrowest segment distal to LSA',
      'category': 'Aorta',
      'modality': '2D'
      },
  {'id': 'dao',
      'short_name': 'Desc. Ao',
      'long_name': 'Descending Aorta',
      'timing': 'systole',
      'units': 'mm',
      'view': 'SSN',
      'landmark': 'immed. beyond isthmus',
      'category': 'Aorta',
      'modality': '2D'
  },
    {'id': 'dao_nos',
     'short_name': 'Desc. Ao',
     'long_name': 'Descending Aorta',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'SSN',
     'landmark': 'landmarks not specified in reference',
     'category': 'Aorta',
     'modality': '2D'
     },
  {'id': 'abd_ao',
      'short_name': 'Abd. Ao',
      'long_name': 'Abdominal Aorta',
      'timing': 'systole',
      'units': 'mm',
      'view': 'SUBC',
      'landmark': 'at level of diaphragm',
      'category': 'Aorta',
      'modality': '2D'
      },
# Right heart
  {'id': 'ivc',
      'short_name': 'IVC',
      'long_name': 'Inferior Vena Cava',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'SUBC Sagittal',
      'landmark': 'just below diaphragm',
      'category': 'Veins',
      'modality': '2D'
      },
  {'id': 'ra_major_a4c',
      'short_name': 'RA Major Diameter',
      'long_name': 'RA Major Diameter',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'maximal distance from the center of the tricuspid annulus to the center of the superior RA wall, parallel to the interatrial septum',
      'category': 'Right Atrium',
      'modality': '2D'
    },
  {'id': 'ra_minor_a4c',
      'short_name': 'RA Minor Diameter',
      'long_name': 'RA Minor Diameter',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'maximal distance from the atrial septum to the lateral atrial wall',
      'category': 'Right Atrium',
      'modality': '2D'
    },
  {'id': 'ra_area_a4c',
      'short_name': 'RA Area',
      'long_name': 'RA Area',
      'timing': 'systole',
      'units': 'cm^2',
      'view': 'A4C',
      'landmark': 'endocardial surface, from the lateral aspect of the tricuspid annulus to the septal aspect, excluding the SVC, IVC, and RA appendage',
      'category': 'Right Atrium',
      'modality': '2D'
  },
  {'id': 'tvd_l',
      'short_name': 'TV, Lateral',
      'long_name': 'Tricuspid Valve, Lateral',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'leaflet hingepoints',
      'category': 'AV Valves',
      'modality': '2D',
      },
  {'id': 'tvd_ap',
      'short_name': 'TV, AP',
      'long_name': 'Tricuspid Valve, Antero-Posterior',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'PLAX',
      'landmark': 'leaflet hingepoints',
      'category': 'AV Valves',
      'modality': '2D',
      },
    {'id': 'tv_area',
     'short_name': 'TV, Area',
     'long_name': 'Tricuspid Valve Area',
     'timing': 'diastole',
     'units': 'cm^2',
     'view': '(derived)',
     'landmark': 'n/a',
     'category': 'AV Valves',
     'modality': '2D',
     },
    {'id': 'rv_awt',
     'short_name': 'RV Ant. Wall',
     'long_name': 'RV Anterior Wall Thickness',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'Exclude RV trabeculations, epicardial fat, and papillary muscle from RV endocardial border',
     'category': 'Right Ventricle',
     'modality': '2D'
    },
    {'id': 'rv_fwt',
     'short_name': 'RV Free Wall',
     'long_name': 'RV Free Wall Thickness',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'SUBC',
     'landmark': 'Exclude RV trabeculations, epicardial fat, and papillary muscle from RV endocardial border',
     'category': 'Right Ventricle',
     'modality': '2D'
    },
    {'id': 'rv_b_a4c',
      'short_name': 'RV Base',
      'long_name': 'RV Basal Diameter',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'maximal distance from RV free wall to septum, parallel to annulus, basal 1/3rd of RV',
      'category': 'Right Ventricle',
      'modality': '2D'
    },
  {'id': 'rv_mc_a4c',
      'short_name': 'RVD-MC',
      'long_name': 'RV Mid-Cavitary Diameter',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'RV free wall to septal endocardium, parallel to annulus, midway between annulus and apex',
      'category': 'Right Ventricle',
      'modality': '2D',
    },
  { 'id': 'rv_len',
      'short_name': 'RV-LEN',
      'long_name': 'RV Length',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'midpoint of TV annulus to RV apex',
      'category': 'Right Ventricle',
      'modality': '2D',
    },
  {'id': 'rv_len_es',
      'short_name': 'RV-LEN-ES',
      'long_name': 'RV Length, End-Systole',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'midpoint of TV annulus to RV apex',
      'category': 'Right Ventricle',
      'modality': '2D',
  },
  { 'id': 'rv_b_plax',
      'short_name': 'RV Base, PLAX',
      'long_name': 'RV Anteroinferior Basal Diameter ',
      'timing': 'diastole',
      'units': 'mm',
      'view': 'PLAX',
      'landmark': 'maximal diameter at the basal third of the RV cavity from its anterior to inferior walls while maintaining a parallel orientation with the annulus.',
      'category': 'Right Ventricle',
      'modality': '2D'
    },
    {'id': 'rv_ap_plax',
     'short_name': 'RV AP Diam., PLAX',
     'long_name': 'RV Anteroposterior Diameter ',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PLAX',
     'landmark': 'maximal diameter of RV cavity from its anterior to septal walls.',
     'category': 'Right Ventricle',
     'modality': '2D'
     },
    {'id': 'rvot_psax',
     'short_name': 'RVOT, PSAX',
     'long_name': 'RV Outflow Diameter, PSAX ',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PSAX',
     'landmark': 'From the RV free wall above the aortic valve to the anterior aortic wall.',
     'category': 'Right Ventricle',
     'modality': '2D'
     },
  {'id': 'rv_eda_a4c',
      'short_name': 'RVEDA-A4C',
      'long_name': 'RV End-Diastolic Area (A4C)',
      'timing': 'diastole',
      'units': 'cm^2',
      'view': 'A4C',
      'landmark': 'RV endocardial border (include trabeculations within the area)',
      'category': 'Right Ventricle',
      'modality': '2D'
      },
  {'id': 'rv_esa_a4c',
      'short_name': 'RVESA-A4C',
      'long_name': 'RV End-Systolic Area (A4C)',
      'timing': 'systole',
      'units': 'cm^2',
      'view': 'A4C',
      'landmark': 'Rotated CCW from traditional A4C; RV endocardial border (include trabeculations within the area)',
      'category': 'Right Ventricle',
      'modality': '2D'
      },
  {'id': 'rv_fac_a4c',
      'short_name': 'RV FAC-A4C',
      'long_name': 'RV Fractional Area Change (A4C)',
      'timing': 'n/a',
      'units': '%',
      'view': 'A4C',
      'landmark': '(EDA - ESA) / EDA',
      'category': 'Right Ventricle',
      'modality': '2D'
  },
  {'id': 'rv_eda_3c',
      'short_name': 'RVEDA-3C',
      'long_name': 'RV End-Diastolic Area (RV 3C)',
      'timing': 'diastole',
      'units': 'cm^2',
      'view': 'RV A3C',
      'landmark': 'Rotated CCW from traditional A4C; RV endocardial border (include trabeculations within the area)',
      'category': 'Right Ventricle',
      'modality': '2D'
    },
  {'id': 'rv_esa_3c',
      'short_name': 'RVESA-3C',
      'long_name': 'RV End-Systolic Area (RV 3C)',
      'timing': 'systole',
      'units': 'cm^2',
      'view': 'RV A3C',
      'landmark': 'RV endocardial border (include trabeculations within the area)',
      'category': 'Right Ventricle',
      'modality': '2D'
    },
  {'id': 'rv_fac_3c',
      'short_name': 'RV FAC-3C',
      'long_name': 'RV Fractional Area Change (A3C)',
      'timing': 'n/a',
      'units': '%',
      'view': 'A3C',
      'landmark': '(EDA - ESA) / EDA',
      'category': 'Right Ventricle',
      'modality': '2D'
    },
  {'id': 'rv_fac_global',
      'short_name': 'RV Global FAC',
      'long_name': 'RV Global FAC',
      'timing': 'n/s',
      'units': '%',
      'view': 'Apical',
      'landmark': '(FAC (A4C) + FAC (A3C) / 2',
      'category': 'Right Ventricle',
      'modality': '2D',
  },
  {'id': 'tapse',
      'short_name': 'TAPSE',
      'long_name': 'Tricuspid Annular Plane Systolic Excursion',
      'timing': 'systole',
      'units': 'mm',
      'view': 'A4C',
      'landmark': 'M-Mode through the lateral aspect of the tricuspid annulus while maintaining vertical alignment with the apex',
      'category': 'Right Ventricle',
      'modality': 'M-Mode'
    },
  {'id': 'rv_pls_a4c',
      'short_name': 'RV PLS A4C',
      'long_name': 'RV Peak Longitudinal Strain (A4C)',
      'timing': 'systole',
      'units': '%',
      'view': 'A4C',
      'landmark': 'peak longitudinal strain, RV lateral wall endocardial border, average of the basal, middle, and apical segments',
      'category': 'Right Ventricle',
      'modality': 'STE/Strain'
    },
  {'id': 'rv_pls_3c',
      'short_name': 'RV PLS 3C',
      'long_name': 'RV Peak Longitudinal Strain (A3C)',
      'timing': 'systole',
      'units': '%',
      'view': 'A3C',
      'landmark': 'peak longitudinal strain, average of inferior/anterior wall segments, from the lateral basal attachment of the TV to just before the pulmonary valve attachment at the infundibulum',
      'category': 'Right Ventricle',
      'modality': 'STE/Strain'
    },
  {'id': 'rv_pls_global',
      'short_name': 'RV Global PLS',
      'long_name': 'RV Global Peak Longitudinal Strain',
      'timing': 'n/a',
      'units': '%',
      'view': 'Apical',
      'landmark': '(RV PLS (A4C) + RV PLS (A3C))/2',
      'category': 'Right Ventricle',
      'modality': 'STE/Strain'
    },
  {'id': 'pv',
      'short_name': 'PV',
      'long_name': 'Pulmonary Valve Annulus',
      'timing': 'systole',
      'units': 'mm',
      'view': 'PSAX',
      'landmark': 'leaflet hinge points',
      'category': 'Outlets',
      'modality': '2D',
      },
  {'id': 'pv_d',
     'short_name': 'PV (d)',
     'long_name': 'Pulmonary Valve Annulus (d)',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PSAX',
     'landmark': 'leaflet hinge points',
     'category': 'Outlets',
     'modality': '2D',
  },
  {'id': 'pv_plax',
      'short_name': 'PV PLAX',
      'long_name': 'Pulmonary Valve Annulus, PLAX',
      'timing': 'systole',
      'units': 'mm',
      'view': 'PLAX',
      'landmark': 'leaflet hinge points',
      'category': 'Outlets',
      'modality': '2D',
      },
  {'id': 'mpa',
      'short_name': 'MPA',
      'long_name': 'Main Pulmonary Artery',
      'timing': 'systole',
      'units': 'mm',
      'view': 'PSAX',
      'landmark': 'between the pulmonary sinotubular junction and bifurcation',
      'category': 'Pulmonary Arteries',
      'modality': '2D',
      },
    {'id': 'mpa_d',
     'short_name': 'MPA (d)',
     'long_name': 'Main Pulmonary Artery (d)',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PSAX',
     'landmark': '1 cm distal to PV annulus',
     'category': 'Pulmonary Arteries',
     'modality': '2D',
     },
  {'id': 'rpa',
      'short_name': 'RPA',
      'long_name': 'Right Pulmonary Artery',
      'timing': 'systole',
      'units': 'mm',
      'view': 'PSAX',
      'landmark': 'immediately beyond bifurcation',
      'category': 'Pulmonary Arteries',
      'modality': '2D',
      },
    {'id': 'rpa_d',
     'short_name': 'RPA (d)',
     'long_name': 'Right Pulmonary Artery (d)',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PSAX',
     'landmark': '1 cm beyond bifurcation',
     'category': 'Pulmonary Arteries',
     'modality': '2D',
     },
  {'id': 'lpa',
      'short_name': 'LPA',
      'long_name': 'Left Pulmonary Artery',
      'timing': 'systole',
      'units': 'mm',
      'view': 'PSAX',
      'landmark': 'immediately beyond bifurcation',
      'category': 'Pulmonary Arteries',
      'modality': '2D',
      },
    {'id': 'lpa_d',
     'short_name': 'LPA (d)',
     'long_name': 'Left Pulmonary Artery (d)',
     'timing': 'diastole',
     'units': 'mm',
     'view': 'PSAX',
     'landmark': '1 cm beyond bifurcation',
     'category': 'Pulmonary Arteries',
     'modality': '2D',
     },

    #Doppler
  {'id': 'mv_e',
      'short_name': 'MV E',
      'long_name': 'MV E',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak early diastolic mitral inflow, PW sample volume at leaflet tips',
      'category': 'Left Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'mv_a',
      'short_name': 'MV A',
      'long_name': 'MV A',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak late diastolic mitral inflow, PW sample volume at leaflet tips',
      'category': 'Left Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'mv_ea_ratio',
      'short_name': 'MV E/A',
      'long_name': 'MV E/A ratio',
      'timing': 'diastole',
      'units': '',
      'view': 'apical',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'tv_e',
      'short_name': 'TV E',
      'long_name': 'TV E',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak early diastolic tricuspid inflow, PW sample volume at leaflet tips',
      'category': 'Right Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'tv_a',
      'short_name': 'TV A',
      'long_name': 'TV A',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak late diastolic tricuspid inflow, PW sample volume at leaflet tips',
      'category': 'Right Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'tv_ea_ratio',
      'short_name': 'TV E/A',
      'long_name': 'TV E/A ratio',
      'timing': 'diastole',
      'units': '',
      'view': 'apical',
      'landmark': '',
      'category': 'Right Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'lv_tdi_e',
      'short_name': 'LV TDI E',
      'long_name': 'LV TDI E\'',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak early diastolic annular velocity',
      'category': 'Left Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'lv_tdi_a',
      'short_name': 'LV TDI A',
      'long_name': 'LV TDI A\'',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak late diastolic annular velocity',
      'category': 'Left Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'lv_tdi_s',
      'short_name': 'LV TDI S',
      'long_name': 'LV TDI S\'',
      'timing': 'systole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak systolic annular velocity',
      'category': 'Left Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'septal_tdi_e',
      'short_name': 'Septal TDI E',
      'long_name': 'Septal TDI E\'',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak early diastolic annular velocity',
      'category': 'Left Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'septal_tdi_a',
      'short_name': 'Septal TDI A',
      'long_name': 'Septal TDI A\'',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak late diastolic annular velocity',
      'category': 'Left Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'septal_tdi_s',
      'short_name': 'Septal TDI S',
      'long_name': 'Septal TDI S\'',
      'timing': 'systole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak systolic annular velocity',
      'category': 'Left Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'rv_tdi_e',
      'short_name': 'RV TDI E',
      'long_name': 'RV TDI E',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak early diastolic annular velocity',
      'category': 'Right Ventricle',
      'modality': 'Doppler',
  },
  {'id': 'rv_tdi_a',
      'short_name': 'RV TDI A',
      'long_name': 'RV TDI A',
      'timing': 'diastole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak late diastolic annular velocity',
      'category': 'Right Ventricle',
      'modality': 'Doppler'
  },
  {'id': 'rv_tdi_ea_ratio',
      'short_name': 'RV TDI E/A',
      'long_name': 'RV TDI E/A Ratio',
      'timing': 'diastole',
      'units': '',
      'view': 'apical',
      'landmark': '',
      'category': 'Right Ventricle',
      'modality': 'Doppler'
  },
  {'id': 'rv_tdi_s',
      'short_name': 'RV TDI S',
      'long_name': 'RV TDI S',
      'timing': 'systole',
      'units': 'cm/s',
      'view': 'apical',
      'landmark': 'peak systolic annular velocity',
      'category': 'Right Ventricle',
      'modality': 'Doppler'
  },
    {'id': 'tv_Ee_ratio',
      'short_name': 'TV E/e\'',
      'long_name': 'TV E/e\'',
      'timing': 'diastole',
      'units': '',
      'view': 'apical',
      'landmark': '',
      'category': 'Right Ventricle',
      'modality': 'Doppler'
    },
    {'id': 'paat',
     'short_name': 'PAAT',
     'long_name': 'Pulmonary Artery Acceleration Time',
     'timing': 'systole',
     'units': 'msec',
     'view': 'PSAX',
     'landmark': 'onset of flow to peak velocity',
     'category': 'Pulmonary Arteries',
     'modality': 'Doppler'
     },
    # strain
    {'id': 'mean_ls',
      'short_name': 'Mean LS',
      'long_name': 'Mean Longitudinal Strain',
      'timing': 'systole',
      'units': '%',
      'view': 'apical',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': 'STE'
    },
    {'id': 'basal_mean_cs',
      'short_name': 'Basal Mean CS',
      'long_name': 'Basal Mean Circumferential Strain',
      'timing': 'systole',
      'units': '%',
      'view': 'PSAX',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': 'STE'
    },
    {'id': 'mid_mean_cs',
      'short_name': 'Mid Mean CS',
      'long_name': 'Mid Mean Circumferential Strain',
      'timing': 'systole',
      'units': '%',
      'view': 'PSAX',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': 'STE'
    },
    {'id': 'apical_mean_cs',
      'short_name': 'Apical Mean CS',
      'long_name': 'Apical Mean Circumferential Strain',
      'timing': 'systole',
      'units': '%',
      'view': 'PSAX',
      'landmark': '',
      'category': 'Left Ventricle',
      'modality': 'STE'
    }

]

CATEGORIES = [
    'Atria', 'AV Valves', 'Left Ventricle', 'Right Ventricle', 'Outlets',
    'Aorta', 'Pulmonary Arteries', 'Coronary Arteries'
]

MODALITIES = [
    'M-Mode',
    '2D',
    'Doppler'
]


def getMeasurements(list):
    #return a list of measurement objects given a list of id's
    temp = []
    for item in list:
        for meas in MEASUREMENTS:
             if meas['id'] == item:
                temp.append(meas)
    return temp


def makeMenu(cat):
        #make a list of items suitable for html SELECTs
        #a list of dicts; each containing a list of the categorized sites (themselves dicts)
        temp = [] 
        for item in cat :
                temp.append({
                        item:[meas for meas in MEASUREMENTS if meas['category'] == item]
                         })
        return temp

siteMenu = makeMenu(CATEGORIES)
